# on: push Este es un evento que desencadena el flujo de trabajo cuando se 
# realiza un push a la rama del repositorio en la que se encuentra el archivo YAML.
on: push
# jobs: En este bloque se definen los trabajos que se ejecutarán como parte del flujo de trabajo.
# En este caso, hay un solo trabajo llamado first-job.
jobs:
# first-job: Este es el nombre del trabajo que se ejecutará. 
# Se pueden tener múltiples trabajos definidos en un flujo de trabajo.
  first-job:
# runs-on: windows-latest: Esta es una directiva que especifica el entorno en el 
# que se ejecutará el trabajo. 
# En este caso, el trabajo se ejecutará en la última versión de Windows.
    runs-on: ubuntu-latest
    container: node:17.6.0
# steps: Aquí se definen las tareas que se ejecutarán como parte del trabajo. 
# Cada paso representa una tarea específica que se realizará en el entorno especificado. 
    steps:
      - run: node --version
      - run: npm --version
      